import 'package:flutter/material.dart';

final ColorScheme lightColorScheme = ColorScheme.fromSwatch(
  // primarySwatch: customSwatch,
  brightness: Brightness.light,
).copyWith(
  primary: const Color(0xFF6e7881),
  onPrimary: const Color(0xFFffffff),
  primaryContainer: const Color(0xffc9e6ff),
  onPrimaryContainer: const Color(0xff001e2f),
  secondary: const Color(0xFF4F606E),
  onSecondary: const Color(0xFFffffff),
  secondaryContainer: const Color(0xffd3e5f5),
  onSecondaryContainer: const Color(0xff0b1d29),
  tertiary: const Color(0xFF64597c),
  onTertiary: const Color(0xFFffffff),
  tertiaryContainer: const Color(0xffeaddff),
  onTertiaryContainer: const Color(0xff1f1635),
  error: const Color(0xffba1a1a),
  onError: const Color(0xffffffff),
  errorContainer: const Color(0xffffdad6),
  onErrorContainer: const Color(0xff410002),
  surfaceDim: const Color(0xffd7dadf),
  surface: const Color(0xfff6f9fe),
  surfaceBright: const Color(0xfff6f9fe),
  inverseSurface: const Color(0xff2d3135),
  surfaceContainerLowest: const Color(0xffffffff),
  surfaceContainerLow: const Color(0xfff1f4f9),
  surfaceContainer: const Color(0xffebeef3),
  surfaceContainerHigh: const Color(0xffe5e8ed),
  surfaceContainerHighest: const Color(0xffdfe3e8),
  inversePrimary: const Color(0xff94cdf7),
  onSurface: const Color(0xff181c20),
  onSurfaceVariant: const Color(0xff41474d),
  outline: const Color(0xff71787e),
  outlineVariant: const Color(0xffc1c7ce),
  scrim: const Color(0xff000000),
  shadow: const Color(0xff000000)
);