import 'package:flutter/material.dart';

final ColorScheme lightColorScheme = ColorScheme.fromSwatch(
  // primarySwatch: customSwatch,
  brightness: Brightness.light,
).copyWith(
  primary: const Color(0xFF0340cb),
  onPrimary: const Color(0xFFffffff),
  primaryContainer: const Color(0xff4269f1),
  onPrimaryContainer: const Color(0xffffffff),
  secondary: const Color(0xFF4e5b93),
  onSecondary: const Color(0xFFffffff),
  secondaryContainer: const Color(0xffbec9ff),
  onSecondaryContainer: const Color(0xff28366b),
  tertiary: const Color(0xFF851c96),
  onTertiary: const Color(0xFFffffff),
  tertiaryContainer: const Color(0xffaf49be),
  onTertiaryContainer: const Color(0xffffffff),
  error: const Color(0xffba1a1a),
  onError: const Color(0xffffffff),
  errorContainer: const Color(0xffffdad6),
  onErrorContainer: const Color(0xff410002),
  surfaceDim: const Color(0xffd9d9e4),
  surface: const Color(0xfffbf8ff),
  surfaceBright: const Color(0xfff6f9fe),
  inverseSurface: const Color(0xff2d3135),
  surfaceContainerLowest: const Color(0xffffffff),
  surfaceContainerLow: const Color(0xfff1f4f9),
  surfaceContainer: const Color(0xffebeef3),
  surfaceContainerHigh: const Color(0xffe5e8ed),
  surfaceContainerHighest: const Color(0xffdfe3e8),
  inversePrimary: const Color(0xff94cdf7),
  onSurface: const Color(0xff181c20),
  onSurfaceVariant: const Color(0xff41474d),
  outline: const Color(0xff71787e),
  outlineVariant: const Color(0xffc1c7ce),
  scrim: const Color(0xff000000),
  shadow: const Color(0xff000000)
);