import 'package:flutter/material.dart';

final ColorScheme darkColorScheme = ColorScheme.fromSwatch(
  brightness: Brightness.dark,
).copyWith(
  primary: const Color(0xFFb7c4ff),
  onPrimary: const Color(0xFF002682),
  primaryContainer: const Color(0xFF4269f1),
  onPrimaryContainer: const Color(0xFFffffff),
  secondary: const Color(0xFFb7c4ff),
  onSecondary: const Color(0xFFc4ceff),
  secondaryContainer: const Color(0xFF2b396f),
  onSecondaryContainer: const Color(0xFFc4ceff),
  tertiary: const Color(0xFFfaabff),
  onTertiary: const Color(0xFF570065),
  tertiaryContainer: const Color(0xFFaf49be),
  onTertiaryContainer: const Color(0xFFffffff),
  error: const Color(0xFFffb4ab),
  onError: const Color(0xFF690005),
  errorContainer: const Color(0xFF93000a),
  onErrorContainer: const Color(0xFFffdad6),
  surfaceDim: const Color(0xFF11131b),
  surface: const Color(0xFF11131b),
  surfaceBright: const Color(0xFF232529),
  inverseSurface: const Color(0xFFe6e6ea),
  surfaceContainerLowest: const Color(0xFF121212),
  surfaceContainerLow: const Color(0xFF191a1e),
  surfaceContainer: const Color(0xFF202225),
  surfaceContainerHigh: const Color(0xFF282a2e),
  surfaceContainerHighest: const Color(0xFF2f3237),
  inversePrimary: const Color(0xFF2451d9),
  onSurface: const Color(0xFFe2e1ed),
  onSurfaceVariant: const Color(0xFFb0b0b5),
  outline: const Color(0xFF8d9199),
  outlineVariant: const Color(0xFF4a4c4f),
  scrim: const Color(0xFF000000),
  shadow: const Color(0xFF000000),
);
